title: This Blog belongs to ChrisDev
author: ChrisArias-dev
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This blog is a combation of what I love and it is a great example of what a Blog should be like.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
